import {Inter, Roboto, Roboto_Condensed} from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import {YandexMetrikaContainer} from "@/components/metrics";

const roboto = Roboto({
    variable: "--font-roboto",
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ["latin", "cyrillic"],
});
const inter = Inter({
    variable: "--font-inter",
    weight: ['400', '500'],
    subsets: ["latin", "cyrillic"],
});

const robotoCondensed = Roboto_Condensed({
    variable: "--font-roboto-condensed",
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ["latin", "cyrillic"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {

    return (
        <html lang="en">
            <body
                className={`${roboto.variable} ${robotoCondensed.variable} ${inter.variable} font-sans antialiased`}
            >
            <Suspense>
                <YandexMetrikaContainer enabled={true} />
            </Suspense>
            {children}
            </body>
        </html>
    );
}
